package com.debo.traintrip.service.impl;

import static com.debo.traintrip.constants.BookingConstants.BookingStatus.CONFIRMED;
import static com.debo.traintrip.constants.BookingConstants.trainIdToDetailsMap;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;

import com.debo.traintrip.constants.BookingConstants;
import com.debo.traintrip.entity.TrainAndSeatDetails;
import com.debo.traintrip.exception.ReservationFailedException;
import com.debo.traintrip.model.BookingDetails;
import com.debo.traintrip.model.BookingRequest;
import com.debo.traintrip.model.Passenger;
import com.debo.traintrip.model.PassengerSeatDetails;
import com.debo.traintrip.model.SeatDetails;
import com.debo.traintrip.model.TrainBookingDetails;
import com.debo.traintrip.repository.BookingRepository;
import com.debo.traintrip.service.BookingService;
import com.debo.traintrip.validator.RequestValidator;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Service
@Slf4j
@RequiredArgsConstructor
public class BookingServiceImpl implements BookingService {

    private final RequestValidator requestValidator;
    private final BookingRepository bookingRepository;

    @Override
    public BookingDetails purchaseTicket(BookingRequest bookingRequest) {
        // Validate the booking request and then call save and return booking details
        requestValidator.validateBookingRequest(bookingRequest);
        // Fetch seat availability and price from the database(in real application).
        TrainAndSeatDetails trainAndSeatDetails = bookingRepository.getTrainAndSeatDetails(bookingRequest.getTrainNumber());
        int price = bookingRepository.getPriceForTrain(bookingRequest.getFrom(), bookingRequest.getTo());

        // first we will check required number of seats are available or not
        int seatsInSecA = trainAndSeatDetails.getAvailableSeatCount().get(BookingConstants.TrainSection.A);
        int seatsInSecB = trainAndSeatDetails.getAvailableSeatCount().get(BookingConstants.TrainSection.B);
        BookingDetails bookingDetails = BookingDetails.builder()
                .from(bookingRequest.getFrom())
                .to(bookingRequest.getTo())
                .userEmail(bookingRequest.getLoggedInUsername())
                .build();
        if (bookingRequest.getNumberOfSeats() <= (seatsInSecA + seatsInSecB)) {
            // set the total price for the response
            bookingDetails.setPricePaid(price * bookingRequest.getNumberOfSeats());
            // generate booking Id
            generateBookingId(bookingDetails, bookingRequest.getTrainNumber());
            // set the TrainDetails in the bookingDetails object
            updateTrainDetails(bookingDetails, bookingRequest, seatsInSecA, seatsInSecB);
        } else {
            // Not making it complicated by implementing logic for RAC and other statuses
            throw  new ReservationFailedException("Number of seats available is less than " + bookingRequest.getNumberOfSeats());
        }
        // save the booking details in the database/mock database and return response
        bookingRepository.saveBooking(bookingDetails);
        return bookingDetails;
    }

    private void generateBookingId(BookingDetails bookingDetails, String trainNumber) {
        // In a real application, this would be generated by the database or a UUID generator.
        String bookingId = trainNumber + "-" + System.currentTimeMillis() + "-" + (int)(Math.random() * 1000);
        bookingDetails.setBookingId(bookingId);
        log.info("Generated booking ID: {} for train number: {}", bookingDetails.getBookingId(), trainNumber);
    }

    private void updateTrainDetails(BookingDetails bookingDetails, BookingRequest bookingRequest, int seatsInSecA, int seatsInSecB) {
        TrainBookingDetails trainBookingDetails = TrainBookingDetails.builder()
                .trainNumber(bookingRequest.getTrainNumber())
                .build();
        int updatedSeatsInSecA = seatsInSecA;
        int updatedSeatsInSecB = seatsInSecB;

        // First will try to allocate all seats in a single section
        if (bookingRequest.getNumberOfSeats() <= seatsInSecA) {
            // Allocate all seats in section A
            trainBookingDetails.setSectionWiseSeatCount(new HashMap<>(Map.of(BookingConstants.TrainSection.A,
                    bookingRequest.getNumberOfSeats())));
            bookingDetails.setTrainBookingDetails(new ArrayList<>(List.of(trainBookingDetails)));
            updatedSeatsInSecA -= bookingRequest.getNumberOfSeats();
            assignSeats(bookingRequest, trainBookingDetails, bookingRequest.getNumberOfSeats(), 0);
        } else if (bookingRequest.getNumberOfSeats() <= seatsInSecB) {
            // Allocate all seats in section B
            trainBookingDetails.setSectionWiseSeatCount(new HashMap<>(Map.of(BookingConstants.TrainSection.B,
                    bookingRequest.getNumberOfSeats())));
            bookingDetails.setTrainBookingDetails(new ArrayList<>(List.of(trainBookingDetails)));
            updatedSeatsInSecB -= bookingRequest.getNumberOfSeats();
            assignSeats(bookingRequest, trainBookingDetails, 0, bookingRequest.getNumberOfSeats());
        } else {
            /* Allocate seats in both sections. Firstly, allocate all available seats from section A and then allocate remaining
               seats from section B. */
            int seatsInB = bookingRequest.getNumberOfSeats() - seatsInSecA;

            trainBookingDetails.setSectionWiseSeatCount(new HashMap<>(Map.of(BookingConstants.TrainSection.A, seatsInSecA,
                    BookingConstants.TrainSection.B, seatsInB)));
            bookingDetails.setTrainBookingDetails(new ArrayList<>(List.of(trainBookingDetails)));

            updatedSeatsInSecA = 0;
            updatedSeatsInSecB -= seatsInB;
            assignSeats(bookingRequest, trainBookingDetails, seatsInSecA, seatsInB);
        }
        log.info("Updated seats in section A: {} and section B: {} for train number: {}",
                updatedSeatsInSecA, updatedSeatsInSecB, bookingRequest.getTrainNumber());
        // Update the available seat count in the database/mock database
        bookingRepository.updateTrainAndSeatDetails(bookingRequest.getTrainNumber(),
                Map.of(BookingConstants.TrainSection.A, updatedSeatsInSecA,
                        BookingConstants.TrainSection.B, updatedSeatsInSecB));
    }

    private void assignSeats(BookingRequest bookingRequest, TrainBookingDetails trainBookingDetails, int seatsInSecA, int seatsInSecB) {
        // In a real application, this would involve more complex logic to assign specific seats.
        List<PassengerSeatDetails> secASeatDetailsList = new ArrayList<>();
        List<PassengerSeatDetails> secBSeatDetailsList = new ArrayList<>();
        Map<BookingConstants.TrainSection, List<SeatDetails>> sectionToSeatDetailsMap =
                trainIdToDetailsMap.get(bookingRequest.getTrainNumber())
                        .getSectionSeatDetailsMap();
        for (Passenger passenger : bookingRequest.getPassengers()) {
            PassengerSeatDetails passengerSeatDetails = PassengerSeatDetails.builder()
                    .name(passenger.getFirstName() + " " + passenger.getLastName())
                    .age(passenger.getAge())
                    .bookingStatus(CONFIRMED)
                    .gender(passenger.getGender())
                    .build();

            if (seatsInSecA > 0) {
                checkAndAssignSeat(sectionToSeatDetailsMap.get(BookingConstants.TrainSection.A), passengerSeatDetails);
                secASeatDetailsList.add(passengerSeatDetails);
                seatsInSecA--;
            } else {
                checkAndAssignSeat(sectionToSeatDetailsMap.get(BookingConstants.TrainSection.B), passengerSeatDetails);
                secBSeatDetailsList.add(passengerSeatDetails);
                seatsInSecB--;
            }
        }

        trainBookingDetails.setSectionWisePassengerSeatDetails(new HashMap<>(Map.of(
                BookingConstants.TrainSection.A, secASeatDetailsList,
                BookingConstants.TrainSection.B, secBSeatDetailsList)));

    }

    private void checkAndAssignSeat(List<SeatDetails> seats, PassengerSeatDetails passengerSeatDetails) {
        for (SeatDetails seat : seats) {
            if (seat.getBookingStatus() == BookingConstants.BookingStatus.AVAILABLE) {
                seat.setBookingStatus(CONFIRMED); // this will be updated in the database in a real app
                passengerSeatDetails.setSeatNumber(seat.getSeatNumber());
                break;
            }
        }
    }
}
